### ISSUE TITLE
Open Api key leak

### ISSUE THREAD

**Issue by kennarddh** [armandwipangestu/openai-project#3]
I can find your api key in your bundled application.

**Comment by armandwipangestu** [comment]
> I can find your api key in your bundled application.

Where? can you tell me where my API Key is leaked, I am a junior in web development (my knowledge about security is very low)

**Comment by kennarddh** [comment]
![image](https://user-images.githubusercontent.com/79390992/210521028-efec0ce9-73bb-4788-bc57-8313ec54132e.png)

Inside bundled file `main.2a5649ba.js` search `Configuration({apiKey:"` keyword

**Comment by armandwipangestu** [comment]
> Inside bundled file `main.2a5649ba.js` search `Configuration({apiKey:"` keyword

Interesting, I don't know why Vercel or the production .env will show the API Key, for now, I have deleted the variables in Vercel .env to remove my API Key and Redeploy (for recompiling chunk file). Can you give me a reference for troubleshooting this in Vercel?

| Bundled File | Vercel Environment |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/64394320/210687742-a320c2b7-bb69-42dd-bdb4-5286dd8d5be8.png) | ![image](https://user-images.githubusercontent.com/64394320/210687822-514e4b9d-be36-4267-a9c4-bd24565838f9.png) |

**Comment by kennarddh** [comment]
I never used vercel before

If you still want this website to works

You need to create a backend server to proxy all request to open api server

So open api key never included in your frontend bundle

If you want to stop the service you can stop your backend server, You can also implement rate limiting so every user has a limit to call your backend server
